Add Audio to Ubuntu
HRI-EU/AttentiveSupport pull request #6
Opened 2024-11-04 10:52 UTC by NoelHuibers

Adds the Audiopackage to the Dockerimage and ReadMe.
Also updates packages.

2024-11-15 01:12 UTC, felixocker commented on Dockerfile
> +      portaudio19-dev=19.6.0-1.1 && \
adding this line for portaudio requires removing the "&&" at the end of the previous line

2024-11-15 01:18 UTC, felixocker requested changes
thanks for the PR.
could you fix the issue in the Dockerfile or give me edit rights? then this should be good to go

2024-11-17 15:28 UTC, NoelHuibers commented
Fixed it, good that you saw it.

2024-11-17 20:57 UTC, felixocker commented
thanks!

2024-11-17 20:57 UTC, merged